/*
 *CORRIDA DE GRAFOS
 *
 * Escrito por Diego Pedro para a disciplina de Teoria Dos Grafos 2009.2
 */

package telas;

import javax.swing.JOptionPane;
import objetos.*;
import config.DadosDeConfiguracao;
/**
 *
 * @author  PIERRE
 */
public class Apresentacao extends javax.swing.JFrame {
    
    /** Creates new form Apresentacao */
    
    DadosDeConfiguracao config = new DadosDeConfiguracao();
    private final int COLUNA_PLAYER1_INICIAL = 0;
    private final int LINHA_PLAYER1_INICIAL = 0;
    private final int COLUNA_PLAYER2_INICIAL = config.SIZE_COLUNA-1;
    private final int LINHA_PLAYER2_INICIAL = config.SIZE_LINHA-1;
    Personagem P1;
    Personagem P2;
    String nivel = null;
    public Apresentacao() {
        P1 = new Personagem("Alan Mathisson Turing",config.IMGP1,COLUNA_PLAYER1_INICIAL,
                           LINHA_PLAYER1_INICIAL, DadosDeConfiguracao.VERTICE_DESTINO_PLAYER_1,
                           DadosDeConfiguracao.IMGP1_PERCORRIDO);
        P2 = new Personagem("Alan Mathisson Turing","Alan Mathison Turing.jpg",COLUNA_PLAYER2_INICIAL,
                            LINHA_PLAYER2_INICIAL,DadosDeConfiguracao.VERTICE_DESTINO_PLAYER_2,
                            DadosDeConfiguracao.IMGP2_PERCORRIDO);        
        initComponents();
       
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Código Gerado ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        botaoDoisJogadores = new javax.swing.JButton();
        botaoCPU = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Corrida de Grafos");
        setResizable(false);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/nome2.jpg")));
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(60, 40));
        jLabel1.setMinimumSize(new java.awt.Dimension(60, 40));

        botaoDoisJogadores.setText("2 Jogadores");
        botaoDoisJogadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDoisJogadoresActionPerformed(evt);
            }
        });

        botaoCPU.setText("Player1       Vs        CPU");
        botaoCPU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCPUActionPerformed(evt);
            }
        });

        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(botaoDoisJogadores, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoCPU, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(botaoCPU, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(botaoDoisJogadores, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-724)/2, (screenSize.height-479)/2, 724, 479);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
             this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botaoCPUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCPUActionPerformed
       String nome = null;  
       String nivel = null;
        try{
                   while(nome == null || nome.equals("")){
                                nome = JOptionPane.showInputDialog(null, "Digite o nome do Jogador", 
                                                     "Escolha de nome ", 1);
                                if(nome.equals("Alan Mathison Turing")){
                                                JOptionPane.showMessageDialog(null, "Sinto muito mais voce nao pode usar este nome",
                                                                            "NOME NAO PERMITIDO",2);
                                                nome = null;
                                            }
                   }
                    //RECEBE O NIVEL
                    nivel = recebeNivel();
                    while(nivel == null)
                      nivel = recebeNivel();
          this.nivel = nivel;                                                
        }catch(Exception ex){
            return;
        }
        //seta a eficiencia para execução do menor caminho
        P1.setEficienciaMenorCaminho("NORMAL");        
        P2.setEficienciaMenorCaminho(nivel);
        
        P1.setNome(nome);          
        this.dispose();         
        new Tabuleiro(P1,P2).setVisible(true);
    }//GEN-LAST:event_botaoCPUActionPerformed

    private String recebeNivel(){
         String nivel = null;
         try{
            while(nivel == null 
                           || nivel.equals("") 
                           ||(
                               !nivel.equals("FACIL")                             
                               && !nivel.equals("NORMAL")
                               && !nivel.equals("DIFICIL")
                             )
                            ){
                        
                            nivel = JOptionPane.showInputDialog(null, "Escolha o nivel do computador : 'FACIL'"+
                                                                            " 'NORMAL', 'DIFICIL'","Escolha de Nivel",1); 
                                  
                    }
        }catch(Exception ex){
            return null;
        }
        return nivel;
    }
    
    private void botaoDoisJogadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDoisJogadoresActionPerformed
        String nome = null; 
        try{
                    while(nome == null || nome.equals("")){
                                nome = JOptionPane.showInputDialog(null, "Digite o nome do Jogador 1", 
                                                     "Escolha de nome ", 1);
                                if(nome.equals("Alan Mathison Turing")){
                                    JOptionPane.showMessageDialog(null, "Sinto muito mais voce nao pode usar este nome",
                                                                "NOME NAO PERMITIDO",2);
                                    nome = null;
                                }
                    }

                    P1.setNome(nome);
                    nome = null;
                    while(nome == null || nome.equals("")){
                                nome = JOptionPane.showInputDialog(null, "Digite o nome do Jogador 2", 
                                                     "Escolha de nome ", 1);
                               if(nome.equals("Alan Mathison Turing")){
                                    JOptionPane.showMessageDialog(null, "Sinto muito mais voce nao pode usar este nome",
                                                                "NOME NAO PERMITIDO",2);
                                    nome = null;
                                }
                    }
        }catch(Exception ex){
            return;
        }
        P2.setNome(nome);
        P2.setImagem(DadosDeConfiguracao.IMGP2);
        
        //seta a eficiencia para execução do menor caminho
        P1.setEficienciaMenorCaminho("NORMAL");        
        P2.setEficienciaMenorCaminho("NORMAL");
        
        this.dispose();    
        //nivel NORMAL pois sao dois jogadores
        new Tabuleiro(P1,P2).setVisible(true);
    }//GEN-LAST:event_botaoDoisJogadoresActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Apresentacao().setVisible(true);
            }
        });
    }
    
    // Declaração de variáveis - não modifique//GEN-BEGIN:variables
    private javax.swing.JButton botaoCPU;
    private javax.swing.JButton botaoDoisJogadores;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // Fim da declaração de variáveis//GEN-END:variables
    
}
